name: Build recipe

on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: "${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}"
          restore-keys: ${{ runner.os }}-m2
      - name: Cache NPM packages
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm
          restore-keys: ${{ runner.os }}-npm

      - run: npm ci
      - name: lint frontend
        run: npm run lint
      - name: test frontend
        run: npm run test:headless
      - name: build frontend
        run: npm run build

      - name: Build and analyze backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B spotless:check clean verify
